### ISSUE TITLE
Comments: 2014-08-23 fritzcollectd - A collectd plugin to monitor FRITZ!Box routers

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/fetzerch.github.io#3]
Comments for https://fetzerch.github.io/2014/08/23/fritzcollectd/

**Comment by janvonde** [comment]
I am trying to get this up and running, but I am getting the following errors:

> Oct 20 10:54:35 hs2 collectd[30080]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 20 10:54:35 hs2 collectd[30080]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
Oct 20 10:54:55 hs2 collectd[30080]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 20 10:54:55 hs2 collectd[30080]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 40.000 seconds.

I installed fritzcollectd, fritzconnection and collectd via pip on a Ubuntu Linux 16.04 box. At collectd I set the ModulePath for the python plugin to /usr/local/lib/python2.7/dist-packages/. The following files are there:

>✓  root@hs2 ~ $ ll /usr/local/lib/python2.7/dist-packages/
insgesamt 68K
drwxr-sr-x 2 root staff 4.0K Okt 20 09:37 collectd-1.0.dist-info/
-rw-r--r-- 1 root staff 6.7K Okt 20 09:37 collectd.py
-rw-r--r-- 1 root staff 9.0K Okt 20 09:37 collectd.pyc
drwxr-sr-x 2 root staff 4.0K Okt 20 10:48 fritzcollectd-0.2.0.dist-info/
-rw-r--r-- 1 root staff 6.0K Okt 20 10:48 fritzcollectd.py
-rw-r--r-- 1 root staff 6.0K Okt 20 10:48 fritzcollectd.pyc
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 fritzconnection/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 fritzconnection-0.4.6.dist-info/
drwxr-sr-x 6 root staff 4.0K Okt 20 09:23 lxml/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 lxml-3.6.4.dist-info/
drwxr-sr-x 3 root staff 4.0K Okt 20 09:23 requests/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 requests-2.11.1.dist-info/
✓  root@hs2 ~ $ 

When I try to run the python file directly I am getting the following error:
>✓  root@hs2 /usr/local/lib/python2.7/dist-packages $ python fritzcollectd.py
Traceback (most recent call last):
  File "fritzcollectd.py", line 157, in <module>
    collectd.register_config(FC.callback_configure)
AttributeError: 'module' object has no attribute 'register_config'
⚠  root@hs2 /usr/local/lib/python2.7/dist-packages $ 

Do you have an idea what could be wrong in my setup?


Thanks for this great module and for your time,

Jan

**Comment by elyday** [comment]
Hi

**Comment by sckibo** [comment]
Hi all, 
at the moment I am giving the fritzcollectd plugin a try.
My setup is: collectd is supposed to write it's output to influxdb and the I want to read the data from influxdb using grafana.
Regretfully the plugin does not show me anything - Connection status and DLS status are "red" and Disconnected. Any ideas how I could debug the setup?

Here's the output from collectd if I set Verbose to "True" in collectd.conf - so for me it looks like at least my collectd config is working:

Nov 26 12:58:20 Khadas collectd[24340]: fritzcollectd: Calling action: X_AVM-DE_Homeauto:1 GetGenericDeviceInfos {'NewIndex': 1}
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: No readings received
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1-dect0', type: 'power', type_instance: 'power', values: '[0.0]'
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1', type: 'bytes', type_instance: 'lan_totalbytessent', values: '[1800161342]'
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1', type: 'bytes', type_instance: 'lan_totalbytesreceived', values: '[944763477]'
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1-dect0', type: 'power', type_instance: 'energy', values: '[0.0]'
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1-dect0', type: 'temperature', type_instance: 'temperature', values: '[0.0]'
Nov 26 12:58:21 Khadas collectd[24340]: fritzcollectd: Dispatching: host: 'Wohnzimmer', plugin: 'fritzbox', plugin_instance: '1-dect0', type: 'gauge', type_instance: 'switchstate', values: '[0]'

rgds, Martin

**Comment by CalvinSterling** [comment]
@fetzerch 
I've setup fritzcollectd but I get this error from the query in the dashboard.
The traffic graphs work, but the rest do not. 


`
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/query"
params:Object
db:"collectd"
q:"SELECT cumulative_sum(non_negative_difference(last("value"))) FROM "fritzbox_value" WHERE ("type_instance" = 'totalbytesreceived') AND time >= now() - 5m GROUP BY time(2s)"
epoch:"ms"
data:null
precision:"ms"
response:Object
error:"error parsing query: expected field argument in non_negative_difference()"
message:"error parsing query: expected field argument in non_negative_difference()"
`

Here are screenshots. Do you have any idea how to resolve this?
Further, if relevant to the issue, the data in the influxdb is < 24 hours old.

<img width="1858" alt="screen shot 2018-05-29 at 08 04 46" src="https://user-images.githubusercontent.com/14123419/40642329-1688fb1e-631d-11e8-9c8a-2f7194db4d1b.png">
<img width="1855" alt="screen shot 2018-05-29 at 08 04 22" src="https://user-images.githubusercontent.com/14123419/40642332-19e88798-631d-11e8-900d-0a72dcb13a7b.png">

**Comment by CalvinSterling** [comment]
This issue was that Ubuntu 18.04 ships with influxdb version 1.1.1+dfsg1-4, which does not support certain functions used in the sql scrips.
The solution was to download and install and updated influxdb (version > 1.5.0) by following the instructions found at https://docs.influxdata.com/influxdb/v1.5/introduction/installation/

**Comment by tkbi** [comment]
Hi,
may I ask a question ?
I think, I did going true you way to install all nessesary Tools for the python plugin "fritzcollectd", 
and I did it several time, and checked the collect.conf for the right input to use, like you did mention in your blog, but everything Ends in the error :

""fritzcollectd" plugin, but the plugin isn't loaded or didn't Register", 

do you have any idea, what that can be, because I don't find any Information via Google.

best regards Thomas

**Comment by tkbi** [comment]
Hi, I think the Output from Journal give's some further Information, therefore I'll send here:

Mar 05 09:09:40 <thrraspberry> collectd[20008]: python plugin: Error importing module "fritzcollectd".
Mar 05 09:09:40 <therraspberry> collectd[20008]: Unhandled python exception in importing module: ImportError: No module named fritzcollectd
Mar 05 09:09:40 <therraspberry> collectd[20008]: python plugin: Found a configuration for the "fritzcollectd" plugin, but the plugin isn't loaded or didn't register a configuration
Mar 05 09:09:40 <therraspberry> collectd[20008]: Error: Reading the config file failed!
Mar 05 09:09:40 <therraspberry> collectd[20008]: Read the logs for details.
Mar 05 09:09:40 <therraspberry> systemd[1]: collectd.service: Control process exited, code=exited status=1
Mar 05 09:09:40 <therraspberry> systemd[1]: collectd.service: Failed with result 'exit-code'.
Mar 05 09:09:40 <therraspberry> systemd[1]: Failed to start Statistics collection and monitoring daemon.
Mar 05 09:09:50 <therraspberry> systemd[1]: collectd.service: Service hold-off time over, scheduling restart.
Mar 05 09:09:50 <therraspberry> systemd[1]: collectd.service: Scheduled restart job, restart counter is at 4806.
Mar 05 09:09:50 <therraspberry> systemd[1]: Stopped Statistics collection and monitoring daemon.
Mar 05 09:09:50 <therraspberry> systemd[1]: Starting Statistics collection and monitoring daemon...
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "syslog" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "battery" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "cpu" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "df" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "disk" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "entropy" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "interface" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "irq" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "load" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "memory" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "network" successfully loaded.
Mar 05 09:09:50 <therraspberry> collectd[20013]: plugin_load: plugin "nginx" successfully loaded.
Mar 05 09:09:50  collectd[20013]: plugin_load: plugin "processes" successfully loaded.
