### ISSUE TITLE
Comments: 2014-11-15 Reverse engineering 433 MHz sensors

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/fetzerch.github.io#4]
Comments for https://fetzerch.github.io/2014/11/15/reveng433/

**Comment by swil85** [comment]
Hi, 
nice work,
i'm trying to do the same,
but dont understant the decode part !
I had collected some data like this [showTepm20.zip](https://github.com/fetzerch/fetzerch.github.io/files/2392809/showTepm20.zip)
But stuck here !
Can you explain me how to decode this ?
Thank you in advance.

**Comment by ceritium** [comment]
Hi!

Could you share which model device are you using ?

Thanks.

**Comment by swil85** [comment]
Hi, 
there is one of my post on let's control it : https://www.letscontrolit.com/forum/viewtopic.php?f=10&t=6040
with detailled data.

Hope you can help me.

Thank you in advance.
