### ISSUE TITLE
Comments: 2015-05-20 atMETEO - An ATmega based weather station 

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/fetzerch.github.io#5]
Comments for http://fetzerch.github.io/2015/05/20/atmeteo/

**Comment by joel-bourquard** [comment]
Hi,
Do you know where I could find a Hideki TS53 sensor on sale? I have one from 2008 that is broken, and I can't seem to find that model anymore.

**Comment by fetzerch** [comment]
https://www.bresser.de/Wetter-Zeit/Zusaetzliche-Aussensender/BRESSER-Thermo-Hygro-Funksensor-5CH.html for example but these days they are rather expensive.
